### ISSUE TITLE
[Question] Is there a way to setup websocket without terminal?

### ISSUE THREAD

**Issue by beratgashi** [paragi/PHP-websocket-client#10]
Hi Paragi,

Seems like a really simple websocket client just what I needed, but can I need this to use only to send a notification to the dashboard when clients makes a payment in frontend, so is it possible to run websocket server without terminal for example when the clients starts the session on my site?

Thanks and Regards,
Berat

**Comment by paragi** [comment]
hmm - I'm unsure of your setup.Could you describe it in more detail?
How is your dashboard interface to the server?

A few points:

- PHP-websocket-client lets the server side script, act as a client to another server. 
- The users browser has it's own websocket interface build-in

So if your dashboard is a websocket server, you will be able to use PHP-websocket-client, to make the webserver update the dashboard.

Dose this help?
Best regards Simon
