### ISSUE TITLE
[Question] check connection status

### ISSUE THREAD

**Issue by cabelito** [paragi/PHP-websocket-client#12]
Hi Paragi,
Really good class for PHP. I started using it, however I only use this class to send notifications (one-way) from my server to another websocket server. The only problem I am facing right now is that if for some reason the connection has beed dropped I have to restart my PHP server script because it has to reconnect to the server( websocket) again.
Is there a way to check if connection is alive or it was dropped , so I can reconnect using websocket_open ?

My scenario is:
I open new connection with websocket_open
and then I send notifications using websocket_write

but if in the meantime connection is dropped, my websocket_write function shows ERROR messages that it was unable to send messages? I want to check the connection before writing

**Comment by cabelito** [comment]
Hi all , 
Looks like I found a solution
using feof($sp) returns true if connection was dropped
so:
if (feof($sp) === true) { reconnect } else { we are still connected }

**Comment by mega-giffelen** [comment]
Great.
You are welcome to add ypur solusion to the the README.md if you feel like it.

**Comment by paragi** [comment]
Great. I didn't even have to do anything :)
Please feel free to add your solution to the REAMDE.md
