### ISSUE TITLE
Cant seem to connect to Ratchet thru ProxyPass with ssl

### ISSUE THREAD

**Issue by tesla-srt** [paragi/PHP-websocket-client#13]
Any ideas?

**Comment by paragi** [comment]
Hi Tesla-srt
Thank you for sharing.

I have opened the discussions tab: https://github.com/paragi/PHP-websocket-client/discussions
would you please move your question to that section, as I don't believe i belongs in issues.
Also it would help with an example with results....

Best regards, Simon

**Comment by tesla-srt** [comment]
That's my fault I did not see the discussion
