### ISSUE TITLE
read method mistyped

### ISSUE THREAD

**Issue by chwpi** [paragi/PHP-websocket-client#24]
`$payload_len += ord($header` needs to be `$payload_len += ord($ext` in websocket_read

**Comment by Trismegiste** [comment]
I think you're referring to https://github.com/paragi/PHP-websocket-client/blob/a40a6bf0525a1e76950d19b41201ccccb80bf9cd/src/Client.php#L256 if I understand correctly ?

I agree, it seems a little _odd_ but I don't understand the subtleties of Web Socket Protocol. 
We need more info from @paragi about this.

**Comment by cp-helsinge** [comment]
The job of this function, is to read a 7 bit, 2 or 8 byte integer, in a specific order (Little-endian), describing the length of the payload.
If i understand your suggestion right? you suggest to use the length of that integer (not the value) as payload length. 
That doesn't give meaning to me, so i guess I don't really understand your point?

Du you have a concrete problem to solve? test case?

**Comment by chwpi** [comment]
> 

Yes and the function read the header which is totally ridiculous and wrong, Please read https://www.rfc-editor.org/rfc/rfc6455#section-5.2

`// Get payload length extensions
    $ext_len = 0;
    if($payload_len >= 0x7E){
      $ext_len = 2;
      if($payload_len == 0x7F) $ext_len = 8;
      $ext=fread($sp,$ext_len);
      if(!$ext) die("Reading header extension from websocket failed");

      // Set extented paylod length
      $payload_len= 0;
      for($i=0;$i<$ext_len;$i++) 
        $payload_len += ord($ext[$i]) << ($ext_len-$i-1)*8;
    }`

That is the code block I am using, which works perfectly. Otherwise you get the wrong payload length. It is a simple programming error. They even created the $ext variable but never used it - until I fixedthe error, whcih is to change ord($header[ and replace with ord($ext[ 

I am communicating with a Tornado websocket server, which seems to be coded very sloppy in the first place, please let me know if I should be raising the issue with Tornado(I'm pretty sure it isn't a Tornado issue). 

So far the only Tornado issue is when opening the connection, here is my code
`      || !strpos($response_header,'Sec-Websocket-Accept: ')){ #Sec-WebSocket-Accept case sensitive, tornado implementation is Sec-Websocket`

RFC6455 has Sec-WebSocket, but Tornado replies with Sec-Websocket. And this PHP code is case sensitive. We could wrap the whole thing in strtolower() so it doesn't care, but that's making up for sloppy work.

**Comment by chwpi** [comment]
> The job of this function, is to read a 7 bit, 2 or 8 byte integer, in a specific order (Little-endian), describing the length of the payload. If i understand your suggestion right? you suggest to use the length of that integer (not the value) as payload length. That doesn't give meaning to me, so i guess I don't really understand your point?
> 
> Du you have a concrete problem to solve? test case?

it looks like the code referenced above instead changed the fread() to overwrite $header, which makes the block of code below it work without issue. 

`$header=fread($sp,$ext_len);`
That works OK

**Comment by paragi** [comment]
Your proposal:
`// Get payload length extensions
$ext_len = 0;
if($payload_len >= 0x7E){
$ext_len = 2;
if($payload_len == 0x7F) $ext_len = 8;
$ext=fread($sp,$ext_len);
if(!$ext) die("Reading header extension from websocket failed");

  // Set extented paylod length
  $payload_len= 0;
  for($i=0;$i<$ext_len;$i++) 
    $payload_len += ord($ext[$i]) << ($ext_len-$i-1)*8;
}`

The only difference i can spot, is that you propose to introduce an extra string variable $ext to hold the headerbytes of the payload length, instead of reusing  the spend $header variable.
Is that correct? 

'Yes and the function read the header which is totally ridiculous and wrong, Please read https://www.rfc-editor.org/rfc/rfc6455#section-5.2'
Please clarify?
