### ISSUE TITLE
[Feature] Set custom path in the header

### ISSUE THREAD

**Issue by NabiKAZ** [paragi/PHP-websocket-client#8]
Currently just can be send request for `/` path.
Needed set custom path in the header after `GET`

https://github.com/paragi/PHP-websocket-client/blob/cefdf416d96d01733bd6e62b9ba0ddbbe5888e96/websocket_client.php#L70

**Comment by NabiKAZ** [comment]
I created a PR #9

**Comment by paragi** [comment]
Thanks for your contribution. It is appreciated.
